# ruff: noqa: E501
"""The dbt marts schema the prompt describes, as data.

Generated by `scripts/generate_marts_schema.py` from
`dbt/models/marts/schema.yml`. Do not edit by hand: a test re-runs that parse
and fails when this file differs from it, so a model, a column or a
description edited without a regeneration is a red test rather than a column
the agent has to guess at in production.

Committed rather than read at run time because the serving image ships
without the dbt project: `Dockerfile.agent` copies `pipeline/` and the schema
file is not in it, so every allowlisted table was skipped as undescribed and
the prompt went out with an empty table listing. A listing that is a module
of the package is there wherever the prompt is, including
`python -m pipeline.eval --remote` and any caller with no dbt tree beside it.
See docs/agent-service.md.

Descriptions are the full text from the schema file with their whitespace
collapsed. The prompt cuts them to a sentence and to a character budget when
it renders, so `pipeline.prompts.MAX_TABLE_CHARS` and `MAX_COLUMN_CHARS` can
change without a regeneration.
"""

from typing import Final

# One column of one model: its name and its description.
MartsColumn = tuple[str, str]
# One model: its name, its description and its columns in file order.
MartsModel = tuple[str, str, tuple[MartsColumn, ...]]

MARTS_MODELS: Final[tuple[MartsModel, ...]] = (
    (
        "fct_game_side",
        "The fact table, one row per (game, seat) and two rows per game. Every question the marts answer is a group-by over this grain: a win rate is an average of `is_win`, a matchup is a group-by on the two archetype keys, and a player's record is a group-by on `player_key`. The opponent's archetype is denormalized onto the row so a matchup never needs a self-join. Nothing is filtered here, including games the uploader excluded from statistics: the marts drop those, and a fact that had already dropped them could not answer how many there were.",
        (
            (
                "game_side_key",
                "Surrogate key, the game identifier and the seat index joined by a hyphen. The grain of this table.",
            ),
            (
                "game_id",
                "The game this seat belongs to.",
            ),
            (
                "seat",
                "Seat index within the game. Silver numbers seats 0 and 1, following the contract's `players` array, so these are the accepted values here too.",
            ),
            (
                "is_uploader",
                "This seat belongs to the member who uploaded the game. At most one seat per game, and neither when the parser could not resolve the uploader.",
            ),
            (
                "player_key",
                "Foreign key to dim_player, or NULL. A stranger, somebody who was matched against a member and never uploaded anything, has no token in silver and therefore no key here (docs/data-handling.md). The relationship test below is scoped to the non-null rows for that reason.",
            ),
            (
                "archetype_key",
                "Foreign key to dim_archetype for this seat's deck. NULL when the game named no archetype for the seat.",
            ),
            (
                "opponent_archetype_key",
                "Foreign key to dim_archetype for the other seat's deck, denormalized so a matchup is one group-by rather than a self-join.",
            ),
            (
                "season_key",
                "Foreign key to dim_season. Games with no season trailer point at the synthetic `unknown` row rather than carrying a null.",
            ),
            (
                "format_key",
                "Foreign key to dim_format. Derived from the export variant, which is a placeholder, see that model's description.",
            ),
            (
                "date_key",
                "Foreign key to dim_date, the date the game was played.",
            ),
            (
                "result_for_seat",
                "This seat's result. Mirrored from the uploader's result for the other seat, and `unknown` when no seat could be resolved.",
            ),
            (
                "is_win",
                "True when this seat won. Summing it is the win count.",
            ),
            (
                "is_loss",
                "True when this seat lost.",
            ),
            (
                "is_tie",
                "True when the game was a tie, which only happens on a hand-logged game.",
            ),
            (
                "went_first",
                "This seat took the first turn.",
            ),
            (
                "turn_count",
                "Turns in the whole game, carried from the game grain so a seat row is self-contained. Zero for a hand-logged game.",
            ),
            (
                "prizes_taken",
                "Prize cards this seat took. NULL for a hand-logged game, which carries no counters.",
            ),
            (
                "knockouts",
                "Opposing Pokemon this seat knocked out.",
            ),
            (
                "cards_drawn",
                "Cards this seat drew.",
            ),
            (
                "energy_attached",
                "Energy cards this seat attached.",
            ),
            (
                "damage_dealt",
                "Total damage this seat dealt.",
            ),
            (
                "mulligans",
                "Mulligans this seat had to take.",
            ),
            (
                "turns_taken",
                "Turns this seat took, which is roughly half the game's turn count.",
            ),
            (
                "decklist_complete",
                "This seat shared a full 60-card list in game.",
            ),
            (
                "decklist_card_count",
                "Cards in the list this seat shared. NULL when it shared none.",
            ),
            (
                "has_full_decklists",
                "Both seats of this game shared a complete list.",
            ),
            (
                "export_variant",
                "The shape of the text the game was parsed from.",
            ),
            (
                "excluded_from_stats",
                "The uploader asked for this game to be kept out of analytics. Every mart drops these rows; this table keeps them so the count is answerable.",
            ),
            (
                "upload_count",
                "Blobs in bronze carrying this game id, a game-level attribute carried onto the seat row because there is no game dimension. Two means both players uploaded the same match and silver kept the first upload, so this table still has exactly two rows for it. At least 1 by construction, which `assert_upload_count_is_at_least_one` checks.",
            ),
        ),
    ),
    (
        "dim_player",
        "One row per member, a player who uploaded at least one game and therefore saw the in-app notice. Strangers are absent by construction: silver writes their token as NULL, so there is nothing here to be a row (docs/data-handling.md). The key is the keyed token itself, never a handle.",
        (
            (
                "player_key",
                "The member's keyed token, a hash-based message authentication code over their handle. The surrogate key and the grain.",
            ),
            (
                "first_seen",
                "Play date of their earliest game in the corpus.",
            ),
            (
                "last_seen",
                "Play date of their most recent game.",
            ),
            (
                "games_played",
                "Seats this token holds, counting the games where they were the opponent of another member as well as their own uploads.",
            ),
            (
                "games_uploaded",
                "Games they uploaded themselves.",
            ),
        ),
    ),
    (
        "dim_archetype",
        "One row per archetype. Keyed by the shared archetype row's identifier when a game carries one and by the canonical name otherwise, so an archetype the application has not yet given a row still gets a stable key. The name is the canonical one silver resolved through the alias map it builds from bronze, and `aliases` keeps every raw label the archetype has arrived under so a rename upstream is visible here rather than erased.",
        (
            (
                "archetype_key",
                "Surrogate key, the shared archetype identifier or the lowercased canonical name prefixed with `name:`.",
            ),
            (
                "archetype_name",
                "The canonical display name. Single valued per key because silver has already collapsed the aliases onto it.",
            ),
            (
                "is_name_keyed",
                "True when the key is a name rather than a shared archetype identifier, which means the application has no archetype row for this deck yet.",
            ),
            (
                "aliases",
                "Every distinct raw label this archetype has appeared under, sorted and joined by a pipe character.",
            ),
            (
                "first_seen",
                "Play date of the earliest game this archetype appears in.",
            ),
            (
                "last_seen",
                "Play date of the most recent one.",
            ),
            (
                "games_played",
                "Seats this archetype has held across the corpus, before any exclusion filter.",
            ),
        ),
    ),
    (
        "dim_season",
        "One row per competitive season, plus a synthetic `unknown` row. A season is only recorded when the debug client printed the season trailer, so most games have none; pointing those at `unknown` keeps them joinable instead of losing them to every inner join.",
        (
            (
                "season_key",
                "The season identifier, or the literal `unknown`.",
            ),
            (
                "season_name",
                "Display name of the season.",
            ),
            (
                "is_known",
                "False on the synthetic row, true on a real season. The column exists so a query can exclude the placeholder without matching on a string.",
            ),
            (
                "first_seen",
                "Play date of the earliest game in this season.",
            ),
            (
                "last_seen",
                "Play date of the most recent one.",
            ),
            (
                "games",
                "Games in this season.",
            ),
        ),
    ),
    (
        "dim_format",
        "A placeholder dimension, kept honest by this description. There is no format anywhere in the contract or in silver: the export never names the ruleset a game was played under, so nothing upstream can be keyed on it. The key is the export variant, which describes the shape of the text the game was parsed from and is not a format at all, plus an `unknown` row. The dimension is kept rather than dropped so the fact has a stable `format_key` slot for the day the producer starts recording a real format: adding a column to a fact is a smaller change than adding a dimension to a star schema.",
        (
            (
                "format_key",
                "The export variant (stock, debug or manual), or the literal `unknown`. Standing in for a real format key.",
            ),
            (
                "format_name",
                "Display label, prefixed so a reader cannot mistake it for a real format name.",
            ),
            (
                "is_real_format",
                "False on every row today. It becomes true when the producer starts recording a format and this dimension stops being a placeholder.",
            ),
        ),
    ),
    (
        "dim_card",
        "One row per card observed anywhere in the corpus, with the catalog columns silver had already joined on. Built from the observed cards rather than from the card catalog file, because the catalog is a large export that is not committed and not always fetched, and a dimension that failed without it would make the whole gold stage depend on an optional file. A card nobody has played therefore has no row, which is the right size for a dimension whose only readers are the facts.",
        (
            (
                "card_key",
                "The card's identity as silver resolves it, the client card identifier, else the base card identifier, else the lowercased printed name.",
            ),
            (
                "card_name",
                "The card's name, preferring the catalog's spelling over the battle log's.",
            ),
            (
                "base_card_id",
                "The printing-independent identifier, when any reference carried one.",
            ),
            (
                "set_code",
                "Set code as a reference printed it.",
            ),
            (
                "number",
                "Collector number as a reference printed it.",
            ),
            (
                "catalog_name",
                "Name from the card catalog. NULL when the catalog was not fetched before the silver run.",
            ),
            (
                "catalog_set",
                "Set from the catalog.",
            ),
            (
                "catalog_type",
                "Card type from the catalog, for example Pokemon, Trainer or Energy.",
            ),
            (
                "catalog_hp",
                "Hit points from the catalog, for a Pokemon.",
            ),
            (
                "catalog_reg",
                "Regulation mark from the catalog, which is what decides current-format legality.",
            ),
            (
                "in_catalog",
                "The catalog knew this card's key. False means either the catalog is missing or the key is a printed name the catalog does not index.",
            ),
            (
                "first_seen",
                "Play date this card was first observed.",
            ),
            (
                "last_seen",
                "Play date it was most recently observed.",
            ),
        ),
    ),
    (
        "dim_date",
        "One row per play date that has at least one game, not a gap-free calendar. International Organization for Standardization (ISO) week numbering is used, so a week starts on a Monday and late December can belong to week 1 of the next ISO year, which is why `iso_year` sits next to `year`.",
        (
            (
                "date_key",
                "The play date itself, used directly as the key so the fact needs no lookup to filter on a date range.",
            ),
            (
                "play_date",
                "The same date, named as the lake names it.",
            ),
            (
                "iso_year",
                "ISO week-numbering year, which can differ from the calendar year in the first and last days of a year.",
            ),
            (
                "iso_week",
                "ISO week number, 1 through 53.",
            ),
            (
                "week_start",
                "The Monday that starts this ISO week.",
            ),
            (
                "year",
                "Calendar year.",
            ),
            (
                "month",
                "Calendar month number, 1 through 12.",
            ),
            (
                "month_name",
                "Month name in English.",
            ),
            (
                "iso_day_of_week",
                "Day of the week, 1 for Monday through 7 for Sunday.",
            ),
            (
                "day_name",
                "Day name in English.",
            ),
        ),
    ),
    (
        "mart_matchups",
        "Archetype A against archetype B, one row per ordered pair, so the application can look up either direction with a single equality. The symmetry is a property of the grain rather than a union: a game puts one row in the fact per seat, and each of those rows carries its own archetype and the other seat's, so the same game is counted once as (A, B) and once as (B, A). Games the uploader excluded from statistics are dropped, and so are seats with no archetype on either side. A mirror row, (A, A), counts each mirror game twice, once from each seat, and its wins and losses are equal by definition.",
        (
            (
                "matchup_key",
                "Surrogate key, the two archetype keys joined by ` vs `. The grain of this table.",
            ),
            (
                "archetype_key",
                "The archetype the row is written from the point of view of.",
            ),
            (
                "archetype_name",
                "Its canonical display name.",
            ),
            (
                "opponent_archetype_key",
                "The archetype it was facing.",
            ),
            (
                "opponent_archetype_name",
                "The opponent archetype's canonical display name.",
            ),
            (
                "is_mirror",
                "The two keys are the same. A mirror row counts each game twice, once per seat.",
            ),
            (
                "games",
                "Games played in this matchup, counted from the seat that held `archetype_key`.",
            ),
            (
                "wins",
                "Games that seat won.",
            ),
            (
                "losses",
                "Games that seat lost.",
            ),
            (
                "ties",
                "Games that ended in a tie, which only happens on a hand-logged game.",
            ),
            (
                "undecided",
                "Games whose result could not be resolved, usually because the parser could not tell which seat the uploader held.",
            ),
            (
                "win_rate",
                "Wins divided by wins plus losses. NULL when nothing was decided. Ties and unresolved games are left out of the denominator rather than counted as half a win, because neither is evidence about the matchup.",
            ),
            (
                "min_games_met",
                "The matchup has at least `min_games` games, the project variable that defaults to 5. The mart flags thin cells rather than hiding them, so a reader can see how little data there is.",
            ),
            (
                "first_played",
                "Play date of the earliest game in this matchup.",
            ),
            (
                "last_played",
                "Play date of the most recent one.",
            ),
        ),
    ),
    (
        "mart_archetype_weekly",
        "One row per archetype per International Organization for Standardization (ISO) week. Two different counts live here and they are named apart on purpose. `games` counts seat rows, every appearance of the archetype on either side of the table, which is the right numerator for a win rate because a win belongs to a seat. `week_games` counts games once each, taken from the uploader seats only: exactly one seat per game is the uploader, so counting those rows counts each game exactly once without a distinct over the whole fact. `share_of_week` divides the first by the second, so it reads as the share of the week's games this archetype was one of the two decks in, and the column sums to roughly two across a week rather than one.",
        (
            (
                "archetype_week_key",
                "Surrogate key, the archetype key with the ISO year and week. The grain of this table.",
            ),
            (
                "archetype_key",
                "The archetype.",
            ),
            (
                "archetype_name",
                "Its canonical display name.",
            ),
            (
                "iso_year",
                "ISO week-numbering year.",
            ),
            (
                "iso_week",
                "ISO week number.",
            ),
            (
                "week_start",
                "The Monday that starts the week.",
            ),
            (
                "games",
                "Seats this archetype held that week, on either side of the table.",
            ),
            (
                "wins",
                "Those seats that won.",
            ),
            (
                "losses",
                "Those seats that lost.",
            ),
            (
                "ties",
                "Those seats that tied.",
            ),
            (
                "win_rate",
                "Wins divided by wins plus losses, NULL when nothing was decided.",
            ),
            (
                "week_games",
                "Games played that week, counted once each from the uploader seats.",
            ),
            (
                "share_of_week",
                "Seats this archetype held that week divided by the week's games. Reads as how often it was one of the two decks; sums to about two across a week because every game seats two decks.",
            ),
            (
                "min_games_met",
                "The archetype has at least `min_games` seats that week.",
            ),
        ),
    ),
    (
        "mart_archetype_pace",
        "One row per archetype: how fast the deck plays, averaged over every seat that played it. The ten columns are the ten the application computes for a member's own game when it is uploaded, written a second time in SQL so a member's number and the community's number are the same measurement. `int_game_side_pace` holds the definitions one seat at a time; this is the average. Every average skips the seats where its own number is null, and that is not the same set for every column, so `games` is the seats the archetype played rather than the denominator of any one column. A seat whose game was never logged turn by turn is left out entirely.",
        (
            (
                "archetype_key",
                "The archetype. The grain of this table.",
            ),
            (
                "archetype_name",
                "Its canonical display name.",
            ),
            (
                "games",
                "Seats this archetype held with a logged game.",
            ),
            (
                "first_attack_turn",
                "Average turn of its first attack.",
            ),
            (
                "turns_without_attack_share",
                "Average share of its turns with no attack.",
            ),
            (
                "energy_per_turn",
                "Average energy cards attached per turn.",
            ),
            (
                "prizes_by_turn_4",
                "Average prizes taken by the end of turn 4.",
            ),
            (
                "prizes_by_turn_6",
                "Average prizes taken by the end of turn 6.",
            ),
            (
                "prizes_by_turn_8",
                "Average prizes taken by the end of turn 8.",
            ),
            (
                "prizes_by_turn_10",
                "Average prizes taken by the end of turn 10.",
            ),
            (
                "first_prize_turn",
                "Average turn of its first prize.",
            ),
            (
                "first_knockout_turn",
                "Average turn of its first knockout.",
            ),
            (
                "concession_turn",
                "Average turn a concession ended the game.",
            ),
            (
                "min_games_met",
                "At least `min_games` seats are behind the row.",
            ),
        ),
    ),
    (
        "int_game_side_pace",
        "The ten pace numbers for one seat of one game, and the definitions the pace mart averages. Ephemeral, so it is a common table expression inside `mart_archetype_pace` rather than a relation anything can query. It is the second writing of a definition the application already has in TypeScript, and the two are held together by a test rather than by a comment: the gold tests run this over the ten committed fixture games and compare both seats of each against the application's own output (`evals/fixtures/pace/`). Three exclusions carry it, all of them the application's: a seat's counted turns leave out the turn the game was conceded during, the attack share leaves out turn 1 of the player who went first as well, and a line belongs to the seat the log credits it to rather than to the seat whose turn it was.",
        (
            (
                "game_side_key",
                "Surrogate key, the game identifier and the seat index joined by a hyphen. The grain of this table.",
            ),
            (
                "game_id",
                "The game.",
            ),
            (
                "seat",
                "The seat within it.",
            ),
            (
                "archetype_key",
                "The archetype this seat played.",
            ),
            (
                "excluded_from_stats",
                "The uploader excluded this game from statistics.",
            ),
            (
                "counted_turns",
                "Turns this seat took, minus the one it conceded during. NULL when the game has no turn-by-turn log, which is what the mart scopes on.",
            ),
            (
                "first_attack_turn",
                "The first turn this seat attacked, NULL when it never did.",
            ),
            (
                "turns_without_attack_share",
                "Counted turns with no attack over counted turns, to three decimals, with turn 1 of the player who went first left out of both.",
            ),
            (
                "energy_per_turn",
                "Energy cards this seat attached over its counted turns, to three decimals.",
            ),
            (
                "prizes_by_turn_4",
                "Prizes this seat had taken by the end of turn 4 of the game.",
            ),
            (
                "prizes_by_turn_6",
                "Prizes this seat had taken by the end of turn 6 of the game.",
            ),
            (
                "prizes_by_turn_8",
                "Prizes this seat had taken by the end of turn 8 of the game.",
            ),
            (
                "prizes_by_turn_10",
                "Prizes this seat had taken by the end of turn 10 of the game.",
            ),
            (
                "first_prize_turn",
                "The first turn this seat took a prize, NULL when it took none.",
            ),
            (
                "first_knockout_turn",
                "The first turn this seat was credited with a knockout, NULL when it took none.",
            ),
            (
                "concession_turn",
                "The turn a concession ended the game on, NULL when it ended another way. Game level, so both seats carry it.",
            ),
        ),
    ),
    (
        "mart_cards_seen",
        "One row per (archetype, card). seen_rate is the share of games in which the card was observed being played or revealed. It is not a deck inclusion rate: stock exports only reveal played cards. The two rates are kept side by side and labelled for exactly that reason. `inclusion_rate` is computed over the subset of seats that shared a full decklist in game, which is the only subset where the question has an answer, and it is still an observation: silver carries no row per decklist card, so a card counts toward it only when it was both observed and matched to the shared list. Both numbers are lower bounds, `inclusion_rate` a tighter one.",
        (
            (
                "archetype_card_key",
                "Surrogate key, the archetype key and the card key joined by a pipe character. The grain of this table.",
            ),
            (
                "archetype_key",
                "The archetype whose seats the rates are computed over.",
            ),
            (
                "archetype_name",
                "Its canonical display name.",
            ),
            (
                "card_key",
                "The card.",
            ),
            (
                "card_name",
                "The card's name, preferring the catalog's spelling.",
            ),
            (
                "catalog_type",
                "Card type from the catalog, null when the catalog was not fetched.",
            ),
            (
                "games",
                "Seats this archetype held, the denominator of seen_rate.",
            ),
            (
                "games_with_card",
                "Those seats where the card was observed at least once.",
            ),
            (
                "seen_rate",
                "games_with_card divided by games. The share of games in which the card was observed being played or revealed, which is a lower bound on how often it was in the deck.",
            ),
            (
                "decklist_games",
                "Seats this archetype held where the player shared a full decklist in game, the denominator of inclusion_rate.",
            ),
            (
                "decklist_games_with_card",
                "Those decklist-backed seats where the card was observed and matched to the shared list.",
            ),
            (
                "inclusion_rate",
                "decklist_games_with_card divided by decklist_games, NULL when the archetype has no decklist-backed games. Still bounded by observation, because silver exposes no row per decklist card.",
            ),
            (
                "avg_copies_seen",
                "Average copies observed in the games where the card was seen at all. The producer caps observed counts at four except for basic energy.",
            ),
            (
                "max_copies_seen",
                "The most copies observed in any one game.",
            ),
        ),
    ),
    (
        "mart_player_summary",
        "One row per member: their record and the archetype they play most. Members only, and not because of a filter written here: a stranger's token is already NULL in silver, so there is no row to summarize (docs/data-handling.md). Every number is about somebody who uploaded at least one game and saw the notice. Games the uploader excluded from statistics are dropped.",
        (
            (
                "player_key",
                "The member's keyed token. The grain of this table.",
            ),
            (
                "games",
                "Seats this member held, counting games where they were another member's opponent.",
            ),
            (
                "games_uploaded",
                "Games they uploaded themselves.",
            ),
            (
                "wins",
                "Seats they won.",
            ),
            (
                "losses",
                "Seats they lost.",
            ),
            (
                "ties",
                "Seats that tied.",
            ),
            (
                "win_rate",
                "Wins divided by wins plus losses, NULL when nothing was decided.",
            ),
            (
                "favourite_archetype_key",
                "The archetype they have the most seats with, ties broken by key so a rebuild is stable. NULL when none of their games named an archetype.",
            ),
            (
                "favourite_archetype_name",
                "That archetype's canonical display name.",
            ),
            (
                "favourite_archetype_games",
                "Seats they held with it.",
            ),
            (
                "first_seen",
                "Play date of their earliest game.",
            ),
            (
                "last_seen",
                "Play date of their most recent one.",
            ),
        ),
    ),
)
