"""Every relation dbt builds in this project, by name, allowlisted or not.

Generated by `scripts/generate_warehouse_tables.py` from `dbt/models/**/*.sql`.
Do not edit by hand: a test re-runs that glob and fails when this file differs
from it, so a model added, renamed or deleted without a regeneration is a red
test rather than a wrong refusal in production.

Committed rather than globbed at run time because the serving image ships
without the dbt project: `Dockerfile.agent` copies `pipeline/` and the model
files are not in it, so the glob returned nothing there and every invented
table name was reported as a real table being blocked (PLA-198). A list that
is a module of the package is there wherever the validator is, including
`python -m pipeline.eval --remote` and any caller with no dbt tree beside it.
See docs/sql-gate.md.
"""

from typing import Final

WAREHOUSE_TABLES: Final[tuple[str, ...]] = (
    "dim_archetype",
    "dim_card",
    "dim_date",
    "dim_format",
    "dim_player",
    "dim_season",
    "fct_game_side",
    "features_turn",
    "int_game_side_pace",
    "mart_archetype_pace",
    "mart_archetype_weekly",
    "mart_cards_seen",
    "mart_matchups",
    "mart_pipeline_health",
    "mart_player_summary",
    "ml_labeled_side",
    "ml_split_cutoff",
    "run_metrics",
    "stg_cards_seen",
    "stg_game_sides",
    "stg_games",
    "stg_turns",
)
