"""The contract between the producer's parsed-game blobs and this pipeline.

`contract/parsed-blob.schema.json` is the wire format; `models` mirrors it in Pydantic
and `parse_blob` is the one entry point the ingest stage calls.
"""

from pipeline.contract.models import (
    CONTRACT_VERSION,
    Action,
    ActionKind,
    ArchetypeResolution,
    ArchetypeSource,
    CardRef,
    CompetitiveElo,
    ContractError,
    ContractModel,
    Decklist,
    DecklistSource,
    DeckMeta,
    EndReason,
    Entry,
    ExportVariant,
    FieldValue,
    GameResult,
    GameSummary,
    MySideSource,
    ObservedCards,
    ParsedBlobV1,
    ParsedBlobV2,
    PlayedAtSource,
    RoleStats,
    SeasonSource,
    Segment,
    SegmentKind,
    SideStats,
    SubEntry,
    UploadSource,
    parse_blob,
)

__all__ = [
    "CONTRACT_VERSION",
    "Action",
    "ActionKind",
    "ArchetypeResolution",
    "ArchetypeSource",
    "CardRef",
    "CompetitiveElo",
    "ContractError",
    "ContractModel",
    "Decklist",
    "DecklistSource",
    "DeckMeta",
    "EndReason",
    "Entry",
    "ExportVariant",
    "FieldValue",
    "GameResult",
    "GameSummary",
    "MySideSource",
    "ObservedCards",
    "ParsedBlobV1",
    "ParsedBlobV2",
    "PlayedAtSource",
    "RoleStats",
    "SeasonSource",
    "Segment",
    "SegmentKind",
    "SideStats",
    "SubEntry",
    "UploadSource",
    "parse_blob",
]
