"""Write `pipeline/warehouse_tables.py` from the dbt models in this checkout.

    uv run python scripts/generate_warehouse_tables.py
    uv run python scripts/generate_warehouse_tables.py --check

The SQL validator has to tell a table name the model invented from a real
relation it is not allowed to read, and the authority for that is the dbt
project: every model dbt builds is a `.sql` file under `dbt/models/` whose
stem is the relation's name. Until PLA-198 the validator globbed that
directory at run time, which worked in a checkout and found nothing on the
deployed Lambda, because `Dockerfile.agent` copies `pipeline/` and not `dbt/`.

So the glob runs here, at the time somebody edits the models, and its answer
is committed as a module of the package. The list then travels wherever
`pipeline` does: the serving image, `python -m pipeline.eval --remote`, and
any caller with no dbt tree beside it.

`--check` writes nothing and exits 1 when the committed file is not what this
run would write, which is what `tests/test_agent.py` asserts and what makes
the glob the oracle rather than the runtime path. Run the command with no
flag after adding, renaming or deleting a model.
"""

import argparse
import logging
from collections.abc import Sequence
from pathlib import Path
from typing import Final

from pipeline.config import REPO_ROOT
from pipeline.observability import configure_logging, emit_summary
from pipeline.prompts import dbt_model_names

logger = logging.getLogger(__name__)

STAGE: Final = "generate_warehouse_tables"

# Where the generated module lands, beside the code that reads it.
TARGET: Final = REPO_ROOT / "pipeline" / "warehouse_tables.py"

# The header of the generated file, written here so that the generated file
# says what it is to anybody who opens it. Byte stable: nothing in it is a
# date, a path of this machine or a count, so two runs over the same models
# produce the same file and `--check` compares text rather than parsing it.
HEADER: Final = '''"""Every relation dbt builds in this project, by name, allowlisted or not.

Generated by `scripts/generate_warehouse_tables.py` from `dbt/models/**/*.sql`.
Do not edit by hand: a test re-runs that glob and fails when this file differs
from it, so a model added, renamed or deleted without a regeneration is a red
test rather than a wrong refusal in production.

Committed rather than globbed at run time because the serving image ships
without the dbt project: `Dockerfile.agent` copies `pipeline/` and the model
files are not in it, so the glob returned nothing there and every invented
table name was reported as a real table being blocked (PLA-198). A list that
is a module of the package is there wherever the validator is, including
`python -m pipeline.eval --remote` and any caller with no dbt tree beside it.
See docs/sql-gate.md.
"""

from typing import Final

'''

NAMES_OPEN: Final = "WAREHOUSE_TABLES: Final[tuple[str, ...]] = (\n"
NAMES_CLOSE: Final = ")\n"


def render(names: Sequence[str]) -> str:
    """The whole text of the generated module, for these relation names.

    Sorted, so the file's diff is the model that changed and not the order a
    filesystem happened to walk a directory in.
    """
    lines = "".join(f'    "{name}",\n' for name in sorted(names))
    return f"{HEADER}{NAMES_OPEN}{lines}{NAMES_CLOSE}"


def generate(target: Path = TARGET) -> tuple[str, int, bool]:
    """The text this checkout's models render to, how many, and whether `target` holds it.

    Raises when the glob finds nothing. An empty list is never a real answer:
    it is a run from the wrong directory or against a checkout with no dbt
    project, and committing it would turn every refusal into `table_not_found`
    silently, which is the failure this whole file exists to end.
    """
    names = dbt_model_names()
    if not names:
        raise SystemExit(
            "generate_warehouse_tables: no dbt models found. Run this from a checkout "
            "that has dbt/models/ in it."
        )
    text = render(sorted(names))
    current = target.read_text(encoding="utf-8") if target.is_file() else ""
    return text, len(names), current == text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python scripts/generate_warehouse_tables.py",
        description="Write pipeline/warehouse_tables.py from the dbt models.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit 1 when the committed file is out of date",
    )
    args = parser.parse_args(argv)
    configure_logging(STAGE)
    text, tables, up_to_date = generate()
    if up_to_date:
        emit_summary(
            logger,
            "warehouse tables already current",
            {"path": str(TARGET), "tables": tables, "written": False},
            text=f"{TARGET} is up to date ({tables} tables)",
        )
        return 0
    if args.check:
        logger.error(
            "warehouse tables are out of date",
            extra={"path": str(TARGET), "command": "scripts/generate_warehouse_tables.py"},
        )
        return 1
    TARGET.write_text(text, encoding="utf-8")
    emit_summary(
        logger,
        "warehouse tables written",
        {"path": str(TARGET), "tables": tables, "written": True},
        text=f"wrote {TARGET} ({tables} tables)",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
