"""Write `pipeline/marts_schema.py` from the dbt marts schema in this checkout.

    uv run python scripts/generate_marts_schema.py
    uv run python scripts/generate_marts_schema.py --check

The same fix as `scripts/generate_warehouse_tables.py`, applied to the other
thing in this package that read the dbt tree at run time. The prompt's schema
listing was rendered at import from `dbt/models/marts/schema.yml`, which does
not exist on the deployed image: `Dockerfile.agent` copies `pipeline/` and
nothing else, so `read_models` found no file, every allowlisted table was
skipped as "not described" and the listing came out empty. The model was then
asked to write SQL against tables it had never been shown, which is where
`games_played` and the other invented columns came from, and the prefix was
about a thousand tokens shorter there than in a checkout.

So the parse runs here, at the time somebody edits the models, and its answer
is committed as a module of the package: the table's name, its description
and one `(name, description)` pair per column, with the whitespace already
collapsed. The prompt's budgets are still applied at render time, so
`MAX_TABLE_CHARS` and `MAX_COLUMN_CHARS` can change without a regeneration.

`--check` writes nothing and exits 1 when the committed file is not what this
run would write, which is what `tests/test_agent.py` asserts. Run the command
with no flag after editing a description, a column or a model in
`dbt/models/marts/schema.yml`.
"""

import argparse
import json
import logging
from collections.abc import Sequence
from pathlib import Path
from typing import Final

from pipeline.config import REPO_ROOT
from pipeline.marts_schema import MartsModel
from pipeline.observability import configure_logging, emit_summary
from pipeline.prompts import marts_models_from_files

logger = logging.getLogger(__name__)

STAGE: Final = "generate_marts_schema"

# Where the generated module lands, beside the code that reads it.
TARGET: Final = REPO_ROOT / "pipeline" / "marts_schema.py"

# The header of the generated file, written here so that the generated file
# says what it is to anybody who opens it. Byte stable: nothing in it is a
# date, a path of this machine or a count, so two runs over the same schema
# produce the same file and `--check` compares text rather than parsing it.
#
# The file-level `noqa` is for the descriptions, which are one line each and
# longer than the line length by design: they are data copied out of the dbt
# schema, and rewrapping them would make the diff of a description edit a
# diff of the whole block.
HEADER: Final = '''# ruff: noqa: E501
"""The dbt marts schema the prompt describes, as data.

Generated by `scripts/generate_marts_schema.py` from
`dbt/models/marts/schema.yml`. Do not edit by hand: a test re-runs that parse
and fails when this file differs from it, so a model, a column or a
description edited without a regeneration is a red test rather than a column
the agent has to guess at in production.

Committed rather than read at run time because the serving image ships
without the dbt project: `Dockerfile.agent` copies `pipeline/` and the schema
file is not in it, so every allowlisted table was skipped as undescribed and
the prompt went out with an empty table listing. A listing that is a module
of the package is there wherever the prompt is, including
`python -m pipeline.eval --remote` and any caller with no dbt tree beside it.
See docs/agent-service.md.

Descriptions are the full text from the schema file with their whitespace
collapsed. The prompt cuts them to a sentence and to a character budget when
it renders, so `pipeline.prompts.MAX_TABLE_CHARS` and `MAX_COLUMN_CHARS` can
change without a regeneration.
"""

from typing import Final

# One column of one model: its name and its description.
MartsColumn = tuple[str, str]
# One model: its name, its description and its columns in file order.
MartsModel = tuple[str, str, tuple[MartsColumn, ...]]

'''

MODELS_OPEN: Final = "MARTS_MODELS: Final[tuple[MartsModel, ...]] = (\n"
MODELS_CLOSE: Final = ")\n"


def _literal(text: str) -> str:
    """One description as a Python string literal, escaped the boring way.

    `json.dumps` and not `repr`, because its output is stable across Python
    versions and quoting styles: a description with an apostrophe in it would
    otherwise flip the quote character and show up as a diff nobody made.
    """
    return json.dumps(text, ensure_ascii=False)


def render(models: Sequence[MartsModel]) -> str:
    """The whole text of the generated module, for these models.

    In the schema file's own order, models and columns both, because that is
    the order a reader of the file sees and the order the listing has always
    been rendered in.
    """
    blocks: list[str] = []
    for name, description, columns in models:
        lines = [f"    (\n        {_literal(name)},\n        {_literal(description)},\n"]
        if columns:
            lines.append("        (\n")
            for column, note in columns:
                lines.append(
                    f"            (\n                {_literal(column)},\n"
                    f"                {_literal(note)},\n            ),\n"
                )
            lines.append("        ),\n")
        else:
            lines.append("        (),\n")
        lines.append("    ),\n")
        blocks.append("".join(lines))
    return f"{HEADER}{MODELS_OPEN}{''.join(blocks)}{MODELS_CLOSE}"


def generate(target: Path = TARGET) -> tuple[str, int, bool]:
    """The text this checkout's schema renders to, how many models, and whether `target` holds it.

    Raises when the parse finds nothing. An empty listing is never a real
    answer: it is a run from the wrong directory or against a checkout with no
    dbt project, and committing it would put the prompt back in the state this
    file exists to end.
    """
    models = marts_models_from_files()
    if not models:
        raise SystemExit(
            "generate_marts_schema: no models found. Run this from a checkout "
            "that has dbt/models/marts/schema.yml in it."
        )
    text = render(models)
    current = target.read_text(encoding="utf-8") if target.is_file() else ""
    return text, len(models), current == text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python scripts/generate_marts_schema.py",
        description="Write pipeline/marts_schema.py from the dbt marts schema.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit 1 when the committed file is out of date",
    )
    args = parser.parse_args(argv)
    configure_logging(STAGE)
    text, models, up_to_date = generate()
    if up_to_date:
        emit_summary(
            logger,
            "marts schema already current",
            {"path": str(TARGET), "models": models, "written": False},
            text=f"{TARGET} is up to date ({models} models)",
        )
        return 0
    if args.check:
        logger.error(
            "marts schema is out of date",
            extra={"path": str(TARGET), "command": "scripts/generate_marts_schema.py"},
        )
        return 1
    TARGET.write_text(text, encoding="utf-8")
    emit_summary(
        logger,
        "marts schema written",
        {"path": str(TARGET), "models": models, "written": True},
        text=f"wrote {TARGET} ({models} models)",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
